services:
  php:
    build:
      context: "./docker/php"
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    container_name: google-fonts-php
    volumes:
      - .:/app
    environment:
      - PHP_VERSION=${PHP_VERSION:-8.2}
      - XDEBUG_ENABLED=${XDEBUG_ENABLED:-0}
    stdin_open: true
    tty: true

